version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: carlosharo/social_balance:latest
    env_file:
      - .env
    volumes:
      - ./social_balance:/var/www/html
    ports:
      - '80:80'
    command: >
      sh -c "chmod +x start-app.sh && ./start-app.sh"
#    depends_on:
#      - db

#  db:
#    image: postgres:16-alpine
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: ${PASSWORD_DB}
#      POSTGRES_USER: ${USER}
#      POSTGRES_DB: ${NAME}
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
#    ports:
#      - '${PORT}:5432' #Localport:Dockerport
#    container_name: postgres_db
#
##  db_test:
##    image: postgres:16-alpine
##    restart: always
##    environment:
##      POSTGRES_PASSWORD: ${PASSWORD_DB}
##      POSTGRES_USER: ${USER}
##      POSTGRES_DB: ${NAME}
##    volumes:
##      - ./postgres-data_test:/var/lib/postgresql/data
##    ports:
##      - '5433:5432' #Localport:Dockerport
##    container_name: postgres_db_test
#
#volumes:
#  postgres-data:
##  postgres-data_test: