version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: carlosharo/social_balance:latest
    env_file:
      - .env
    volumes:
      - ./social_balance:/var/www/html
    ports:
      - '8000:8000'
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_USER: ${USER}
      POSTGRES_DB: ${NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '${PORT}:5432' #puertoLocal:puertoDocker
    container_name: postgres_db

volumes:
  postgres-data:
