from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    CustomTokenObtainPairView,
    JusuariosCreateView,
    JusuariosReadView,
    JusuariosActiveView,
    JusuariosIdView,
    JusuariosUpdateView,
    JusuariosDeactivateView,
    JcorporacionesCreateView,
    JcorporacionesReadView,
    JcorporacionesActiveView,
    JcorporacionesIdView,
    JcorporacionesUpdateView,
    JcorporacionesDeactivateView,
    JdepartamentosCreateView,
    JdepartamentosReadView,
    JdepartamentosActiveView,
    JdepartamentosIdView,
    JdepartamentosUpdateView,
    JdepartamentosDeactivateView,
    JgenerosCreateView,
    JgenerosReadView,
    JgenerosActiveView,
    JgenerosIdView,
    JgenerosUpdateView,
    JgenerosDeactivateView,
    JgeografiaCreateView,
    JgeografiaReadView,
    JgeografiaActiveView,
    JgeografiaIdView,
    JgeografiaUpdateView,
    JgeografiaDeactivateView,
    JrolesCreateView,
    JrolesReadView,
    JrolesActiveView,
    JrolesIdView,
    JrolesUpdateView,
    JrolesDeactivateView,
)


urlpatterns = [
    path("login/", CustomTokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("login/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    # CRUD services Users
    path("createUsers/", JusuariosCreateView.as_view(), name="create_users"),
    path("allUsers/", JusuariosReadView.as_view(), name="list_users"),
    path("activeUsers/", JusuariosActiveView.as_view(), name="list-activeusers"),
    path("idUsers/<int:pk>/", JusuariosIdView.as_view(), name="id-users"),
    path("updateUsers/<int:pk>/", JusuariosUpdateView.as_view(), name="update-users"),
    path("deleteUsers/<int:pk>/", JusuariosDeactivateView.as_view(), name="delete-users"),
    # CRUD services Corporation
    path("createCorporations/", JcorporacionesCreateView.as_view(), name="create-corporations"),
    path("allCorporations/", JcorporacionesReadView.as_view(), name="list-corporations"),
    path("activeCorporations/", JcorporacionesActiveView.as_view(), name="list-activecorporations"),
    path("idCorporation/<int:pk>/", JcorporacionesIdView.as_view(), name="id-corporations"),
    path("updateCorporation/<int:pk>/", JcorporacionesUpdateView.as_view(), name="update-corporations"),
    path("deleteCorporation/<int:pk>/", JcorporacionesDeactivateView.as_view(), name="delete-corporations"),
    # CRUD services Department
    path("createDepartments/", JdepartamentosCreateView.as_view(), name="create-departments"),
    path("allDepartments/", JdepartamentosReadView.as_view(), name="list-departments"),
    path("activeDepartments/", JdepartamentosActiveView.as_view(), name="list-activedepartments"),
    path("idDepartments/<int:pk>/", JdepartamentosIdView.as_view(), name="id-departments"),
    path("updateDepartments/<int:pk>/", JdepartamentosUpdateView.as_view(), name="update-departments"),
    path("deleteDepartments/<int:pk>/", JdepartamentosDeactivateView.as_view(), name="delete-departments"),
    # CRUD services Gender
    path("createGenders/", JgenerosCreateView.as_view(), name="create-genders"),
    path("allGenders/", JgenerosReadView.as_view(), name="list-genders"),
    path("activeGenders/", JgenerosActiveView.as_view(), name="list-activegenders"),
    path("idGenders/<int:pk>/", JgenerosIdView.as_view(), name="id-genders"),
    path("updateGenders/<int:pk>/", JgenerosUpdateView.as_view(), name="update-genders"),
    path("deleteGenders/<int:pk>/", JgenerosDeactivateView.as_view(), name="delete-genders"),
    # CRUD services Geography
    path("createGeography/", JgeografiaCreateView.as_view(), name="create-geography"),
    path("allGeography/", JgeografiaReadView.as_view(), name="list-geography"),
    path("activeGeography/", JgeografiaActiveView.as_view(), name="list-activegeography"),
    path("idGeography/<int:pk>/", JgeografiaIdView.as_view(), name="id-geography"),
    path("updateGeography/<int:pk>/", JgeografiaUpdateView.as_view(), name="update-geography"),
    path("deleteGeography/<int:pk>/", JgeografiaDeactivateView.as_view(), name="delete-geography"),
    # CRUD services Roles
    path("createRoles/", JrolesCreateView.as_view(), name="create-roles"),
    path("allRoles/", JrolesReadView.as_view(), name="list-roles"),
    path("activeRoles/", JrolesActiveView.as_view(), name="list-activeroles"),
    path("idRoles/<int:pk>/", JrolesIdView.as_view(), name="id-roles"),
    path("updateRoles/<int:pk>/", JrolesUpdateView.as_view(), name="update-roles"),
    path("deleteRoles/<int:pk>/", JrolesDeactivateView.as_view(), name="delete-roles"),
]
