from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    CustomTokenObtainPairView,
    JusuariosCreateView,
    JusuariosReadView,
    JusuariosActiveView,
    VusersIdView,
    JusuariosUpdateView,
    JusuariosDeactivateView,
    JcorporacionesCreateView,
    VcorporationsReadView,
    JcorporacionesActiveView,
    VcorporationsIdView,
    JcorporacionesUpdateView,
    JcorporacionesDeactivateView,
    JdepartamentosCreateView,
    VdepartmentsReadView,
    JdepartamentosActiveView,
    VdepartmentsIdView,
    JdepartamentosUpdateView,
    JdepartamentosDeactivateView,
    JdepartamentosByBranchesView,
    JgenerosCreateView,
    JgenerosReadView,
    JgenerosActiveView,
    JgenerosIdView,
    JgenerosUpdateView,
    JgenerosDeactivateView,
    JgeografiaCreateView,
    VgeographyReadView,
    JgeografiaActiveView,
    VgeographyIdView,
    JgeografiaUpdateView,
    JgeografiaDeactivateView,
    JrolesCreateView,
    VrolesReadView,
    JrolesActiveView,
    VrolesIdView,
    JrolesUpdateView,
    JrolesDeactivateView,
    JrolesByDepartmentsView,
    JsucursalesCreateView,
    VbranchesReadView,
    JsucursalesActiveView,
    VbranchesIdView,
    JsucursalesUpdateView,
    JsucursalesDeactivateView,
    JsucursalesByCorporationView,
    JtiposidentificacionesCreateView,
    JtiposidentificacionesReadView,
    JtiposidentificacionesActiveView,
    JtiposidentificacionesIdView,
    JtiposidentificacionesUpdateView,
    JtiposidentificacionesDeactivateView,
    JpaginasCreateView,
    JpaginasReadView,
    JprivilegiosCreateView,
    JprivilegiosReadView,
    JpaginasActiveView,
    JpaginasIdView,
    JpaginasUpdateView,
    JpaginasDeactivateView,
    JprivilegiosActiveView,
    JprivilegiosIdView,
    JprivilegiosUpdateView,
    JprivilegiosDeactivateView,
    JprivilegiosByRolesView,
)


urlpatterns = [
    path("login/", CustomTokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("login/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    # CRUD services Users
    path("createUsers/", JusuariosCreateView.as_view(), name="create_users"),
    path("allUsers/", JusuariosReadView.as_view(), name="list_users"),
    path("activeUsers/", JusuariosActiveView.as_view(), name="list-activeusers"),
    path("idUsers/<int:pk>/", VusersIdView.as_view(), name="id-users"),
    path("updateUsers/<int:pk>/", JusuariosUpdateView.as_view(), name="update-users"),
    path("deleteUsers/<int:pk>/", JusuariosDeactivateView.as_view(), name="delete-users"),
    # CRUD services Corporation
    path("createCorporations/", JcorporacionesCreateView.as_view(), name="create-corporations"),
    path("allCorporations/", VcorporationsReadView.as_view(), name="list-corporations"),
    path("activeCorporations/", JcorporacionesActiveView.as_view(), name="list-activecorporations"),
    path("idCorporation/<int:pk>/", VcorporationsIdView.as_view(), name="id-corporations"),
    path("updateCorporation/<int:pk>/", JcorporacionesUpdateView.as_view(), name="update-corporations"),
    path("deleteCorporation/<int:pk>/", JcorporacionesDeactivateView.as_view(), name="delete-corporations"),
    # CRUD services Department
    path("createDepartments/", JdepartamentosCreateView.as_view(), name="create-departments"),
    path("allDepartments/", VdepartmentsReadView.as_view(), name="list-departments"),
    path("activeDepartments/", JdepartamentosActiveView.as_view(), name="list-activedepartments"),
    path("idDepartments/<int:pk>/", VdepartmentsIdView.as_view(), name="id-departments"),
    path("updateDepartments/<int:pk>/", JdepartamentosUpdateView.as_view(), name="update-departments"),
    path("deleteDepartments/<int:pk>/", JdepartamentosDeactivateView.as_view(), name="delete-departments"),
    path("departmentsByBranches/", JdepartamentosByBranchesView.as_view(), name="list-departmentsbybranches"),
    # CRUD services Gender
    path("createGenders/", JgenerosCreateView.as_view(), name="create-genders"),
    path("allGenders/", JgenerosReadView.as_view(), name="list-genders"),
    path("activeGenders/", JgenerosActiveView.as_view(), name="list-activegenders"),
    path("idGenders/<int:pk>/", JgenerosIdView.as_view(), name="id-genders"),
    path("updateGenders/<int:pk>/", JgenerosUpdateView.as_view(), name="update-genders"),
    path("deleteGenders/<int:pk>/", JgenerosDeactivateView.as_view(), name="delete-genders"),
    # CRUD services Geography
    path("createGeography/", JgeografiaCreateView.as_view(), name="create-geography"),
    path("allGeography/", VgeographyReadView.as_view(), name="list-geography"),
    path("activeGeography/", JgeografiaActiveView.as_view(), name="list-activegeography"),
    path("idGeography/<int:pk>/", VgeographyIdView.as_view(), name="id-geography"),
    path("updateGeography/<int:pk>/", JgeografiaUpdateView.as_view(), name="update-geography"),
    path("deleteGeography/<int:pk>/", JgeografiaDeactivateView.as_view(), name="delete-geography"),
    # CRUD services Roles
    path("createRoles/", JrolesCreateView.as_view(), name="create-roles"),
    path("allRoles/", VrolesReadView.as_view(), name="list-roles"),
    path("activeRoles/", JrolesActiveView.as_view(), name="list-activeroles"),
    path("idRoles/<int:pk>/", VrolesIdView.as_view(), name="id-roles"),
    path("updateRoles/<int:pk>/", JrolesUpdateView.as_view(), name="update-roles"),
    path("deleteRoles/<int:pk>/", JrolesDeactivateView.as_view(), name="delete-roles"),
    path("rolesByDepartments/", JrolesByDepartmentsView.as_view(), name="list-rolesbydepartments"),
    # CRUD services Branches
    path("createBranches/", JsucursalesCreateView.as_view(), name="create-branches"),
    path("allBranches/", VbranchesReadView.as_view(), name="list-branches"),
    path("activeBranches/", JsucursalesActiveView.as_view(), name="list-activebranches"),
    path("idBranches/<int:pk>/", VbranchesIdView.as_view(), name="id-branches"),
    path("updateBranches/<int:pk>/", JsucursalesUpdateView.as_view(), name="update-branches"),
    path("deleteBranches/<int:pk>/", JsucursalesDeactivateView.as_view(), name="delete-branches"),
    path("branchesByCorporations/", JsucursalesByCorporationView.as_view(), name="list-brachesbycorporations"),
    # CRUD services TypeId
    path("createTypeId/", JtiposidentificacionesCreateView.as_view(), name="create-typeId"),
    path("allTypeId/", JtiposidentificacionesReadView.as_view(), name="list-typeId"),
    path("activeTypeId/", JtiposidentificacionesActiveView.as_view(), name="list-activetypeId"),
    path("idTypeId/<int:pk>/", JtiposidentificacionesIdView.as_view(), name="id-typeId"),
    path("updateTypeId/<int:pk>/", JtiposidentificacionesUpdateView.as_view(), name="update-typeId"),
    path("deleteTypeId/<int:pk>/", JtiposidentificacionesDeactivateView.as_view(), name="delete-typeId"),
    # CRUD service Pages
    path("createPages/", JpaginasCreateView.as_view(), name="create-pages"),
    path("allPages/", JpaginasReadView.as_view(), name="list-pages"),
    path("activePages/", JpaginasActiveView.as_view(), name="list-activepages"),
    path("idPages/<int:pk>/", JpaginasIdView.as_view(), name="id-pages"),
    path("updatePages/<int:pk>/", JpaginasUpdateView.as_view(), name="update-pages"),
    path("deletePages/<int:pk>/", JpaginasDeactivateView.as_view(), name="delete-pages"),
    # CRUD service Privileges
    path("createPrivileges/", JprivilegiosCreateView.as_view(), name="create-privileges"),
    path("allPrivileges/", JprivilegiosReadView.as_view(), name="list-privileges"),
    path("activePrivileges/", JprivilegiosActiveView.as_view(), name="list-activeprivileges"),
    path("idPrivileges/<int:pk>/", JprivilegiosIdView.as_view(), name="id-privileges"),
    path("updatePrivileges/<int:pk>/", JprivilegiosUpdateView.as_view(), name="update-privileges"),
    path("deletePrivileges/<int:pk>/", JprivilegiosDeactivateView.as_view(), name="delete-privileges"),
    path("privilegesByRoles/", JprivilegiosByRolesView.as_view(), name="list-privilegesbyroles"),
]
